site_name: Pantheos Wiki

theme:
  name: material
  custom_dir: overrides
  features:
    - search.suggest
    - search.highlight
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
exclude_docs: 
  desktop.ini

# tell mkdocs what markdown syntax to use
markdown_extensions:
  # "new line to break" - means it keeps single line breaks in the built html
  - nl2br
  # in order for stat blocks to render correctly, "Markdown in HTML" needs to be enabled
  - md_in_html 

plugins:
  - search
  - awesome-pages
  - inline-select-svg
  - tags:
      tags_hierarchy: true

